Revert "Fix hanging updates after system sleep (#60301)" (#60321)
This reverts commit 2882636c06923e58d83865ecc370bd0d8199d738.

This was causing Zed to crash immediately on startup with the following
error:

```
thread 'main' (74835290) panicked at /Users/maxdeviant/.cargo/git/checkouts/reqwest-dc13ba947e7b959e/c156624/src/async_impl/body.rs:365:33:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

Closes FR-118.

Release Notes:

- Reverted https://github.com/zed-industries/zed/pull/60301

zed-upstream: b5c2d8a13f395bbdbaf9cb74bda16bbcb00414d1